# Generated by Django 2.2.2 on 2020-05-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('Email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1500)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('Email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1500)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med', models.CharField(max_length=1500)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('Email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1500)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1500)),
                ('Email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=1500)),
                ('phone_no', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dosage', models.CharField(max_length=1500)),
                ('Duration', models.CharField(max_length=1500)),
                ('Doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.Doctor')),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.Medicines')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.Patient')),
                ('symptoms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.Symptoms')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('invoice', models.FileField(null=True, upload_to='invoice/', verbose_name='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField()),
                ('status', models.CharField(max_length=1500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital_app.Patient')),
            ],
        ),
    ]
